name: omics_cancer_explore
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - plotly
  - dash-bio
  - matplotlib
  - seaborn
  - lifelines
  - pytest
