# .github/workflows/ci-cd-pipeline.yml

name: Python CI/CD Pipeline

# --- Trigger: Run this workflow on pushes to the main branch ---
on:
  push:
    branches: [ "main" ]

# --- Jobs: Define the tasks to be executed ---
jobs:
  test-and-build:
    runs-on: ubuntu-latest # Use a fresh virtual machine running Ubuntu

    steps:
      # --- Step 1: Check out your repository code ---
      - name: Check out code
        uses: actions/checkout@v4

      # --- Step 2: Set up Conda environment ---
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          environment-file: docker/omics_cancer_explore/environment.yml
          activate-environment: omics_cancer_explore
          
      # --- Step 3: Install the project package ---
      - name: Install package in editable mode
        shell: bash -l {0} # Use the activated conda shell
        run: pip install -e .

      # --- Step 4: Run the test suite ---
      - name: Run tests with pytest
        shell: bash -l {0}
        run: pytest -v

      # --- Step 5: Log in to Docker Hub ---
      # This step is only run if the tests pass
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # --- Step 6: Build and push the Docker image ---
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/omics_cancer_explore/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/omics_cancer_analyzer:latest
